# Generated by Django 3.0.3 on 2020-03-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('News', 'News'), ('Sports', 'Sports')], max_length=2000),
        ),
    ]
