# Generated by Django 3.0.3 on 2020-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0003_auto_20200309_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='s_heading',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_heading_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_3',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('News', 'News'), ('Sports', 'Sports'), ('Food', 'Food'), ('Creative', 'Creative'), ('Education', 'Education'), ('Nature', 'Nature'), ('Personality', 'Personality')], max_length=2000),
        ),
    ]
